/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_zcwfeng_jni_customparcel_ZParcel */

#ifndef _Included_top_zcwfeng_jni_customparcel_ZParcel
#define _Included_top_zcwfeng_jni_customparcel_ZParcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_zcwfeng_jni_customparcel_ZParcel
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_top_zcwfeng_jni_customparcel_ZParcel_nativeCreate
  (JNIEnv *, jclass);

/*
 * Class:     top_zcwfeng_jni_customparcel_ZParcel
 * Method:    nativeReadInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_top_zcwfeng_jni_customparcel_ZParcel_nativeReadInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     top_zcwfeng_jni_customparcel_ZParcel
 * Method:    nativeSetDataPosition
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_top_zcwfeng_jni_customparcel_ZParcel_nativeSetDataPosition
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     top_zcwfeng_jni_customparcel_ZParcel
 * Method:    nativeWriteInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_top_zcwfeng_jni_customparcel_ZParcel_nativeWriteInt
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
