/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_zcwfeng_jni_JavaJNIActivity */
// 解决循环Copy的问题 第二次就进不来了
#ifndef _Included_top_zcwfeng_jni_JavaJNIActivity // 如果没有定义这个宏
#define _Included_top_zcwfeng_jni_JavaJNIActivity // 我就定义这个宏
#ifdef __cplusplus // 如果是C++环境
extern "C" { // 全部采用C的方式 不准你函数重载，函数名一样的问题
#endif
#undef top_zcwfeng_jni_JavaJNIActivity_A
#define top_zcwfeng_jni_JavaJNIActivity_A 100L

// 函数的声明

/*
 * Class:     top_zcwfeng_jni_JavaJNIActivity
 * Method:    getStringPwd
 * Signature: ()Ljava/lang/String;
 */
extern "C"
JNIEXPORT jstring
JNICALL Java_top_zcwfeng_jni_JavaJNIActivity_getStringPwd
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
