/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_zcwfeng_zcwffmpeg_FFMpegUtils */
#ifndef _Included_top_zcwfeng_zcwffmpeg_FFMpegUtils
#define _Included_top_zcwfeng_zcwffmpeg_FFMpegUtils
#ifdef __cplusplus
extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#endif
/*
 * Class:     top_zcwfeng_zcwffmpeg_FFMpegUtils
 * Method:    getRotation
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_top_zcwfeng_zcwffmpeg_FFMpegUtils_logMetada
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
